config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do
    post 'contacts' => "contacts#create"
    root 'contacts#contact', as: 'root', via: :all
    get "(:any)" => "contacts#contact", :as => "contact_info"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :first_name, presence: {message: "first_name_error"}
  validates :last_name, presence: {message: "last_name_error"}
  validates :sender_email, presence: {message: "email_error"}
  validates :message, presence: {message: "message_error"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  around_action :switch_locale

  def contact
    #Setting locale to access in view to submit in fornm
    @locale = params[:locale]
  end

  def create
    @contact = Contact.new
    @contact.first_name = params['first-name']
    @contact.last_name = params['last-name']
    @contact.sender_email = params['email']
    @contact.receiver_email = ENV['ADMIN_EMAIL']
    @contact.mobile_no = params['phone']
    @contact.message = params['message']

    if @contact.save
      ContactMailer.send_message(@contact).deliver_later
      redirect_to contact_info_url(params['locale']), notice: 'sent_message'
    else
      render :contact, notice: 'error_message'
    end
  end

  def switch_locale(&action)
    # Used for setting localization
    redirect_to root_url(locale: params[:set_locale]) if params[:set_locale]
    locale = params[:locale].present? && I18n.available_locales.include?(params[:locale].to_sym) && params[:locale].to_sym || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/ContactFrom/ContactFrom_v17/index.html.haml
!!!
= #require "app/assets/stylesheets/fonts/montserrat/Montserrat-Bold.ttf"
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Contact V17
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    / ===============================================================================================
    = favicon_link_tag asset_path("/icons/favicon.ico"), :rel => 'icon', :type =>  'image/png'
    / ===============================================================================================
    = stylesheet_link_tag "/vendor/bootstrap/css/bootstrap.min.css"
    / ===============================================================================================
    = stylesheet_link_tag "/fonts/font-awesome.min.css"
    / ===============================================================================================
    = stylesheet_link_tag "/fonts/icon-font.min.css"
    / ===============================================================================================
    = stylesheet_link_tag "/vendor/animate/animate.css"
    / ===============================================================================================
    = stylesheet_link_tag "/vendor/css-hamburgers/hamburgers.min.css"
    / ===============================================================================================
    = stylesheet_link_tag "/vendor/animsition/css/animsition.min.css"
    / ===============================================================================================
    = stylesheet_link_tag "/vendor/select2/select2.min.css"
    / ===============================================================================================
    = stylesheet_link_tag "/vendor/daterangepicker/daterangepicker.css"
    / ===============================================================================================
    = stylesheet_link_tag "/css/util.css"
    = stylesheet_link_tag "/css/main.css"
    / ===============================================================================================
  %body
    .container-contact100
      .wrap-contact100
        %form.contact100-form.validate-form
          %span.contact100-form-title
            Send Us A Message
          %label.label-input100{:for => "first-name"} Tell us your name *
          .wrap-input100.rs1-wrap-input100.validate-input{"data-validate" => "Type first name"}
            %input#first-name.input100{:name => "first-name", :placeholder => "First name", :type => "text"}/
            %span.focus-input100
          .wrap-input100.rs2-wrap-input100.validate-input{"data-validate" => "Type last name"}
            %input.input100{:name => "last-name", :placeholder => "Last name", :type => "text"}/
            %span.focus-input100
          %label.label-input100{:for => "email"} Enter your email *
          .wrap-input100.validate-input{"data-validate" => "Valid email is required: ex@abc.xyz"}
            %input#email.input100{:name => "email", :placeholder => "Eg. example@email.com", :type => "text"}/
            %span.focus-input100
          %label.label-input100{:for => "phone"} Enter phone number
          .wrap-input100
            %input#phone.input100{:name => "phone", :placeholder => "Eg. +1 800 000000", :type => "text"}/
            %span.focus-input100
          %label.label-input100{:for => "message"} Message *
          .wrap-input100.validate-input{"data-validate" => "Message is required"}
            %textarea#message.input100{:name => "message", :placeholder => "Write us a message"}
            %span.focus-input100
          .container-contact100-form-btn
            %button.contact100-form-btn
              Send Message
        .contact100-more.flex-col-c-m{:style => "background-image: url('images/bg-01.jpg');"}
          .flex-w.size1.p-b-47
            .txt1.p-r-25
              %span.lnr.lnr-map-marker
            .flex-col.size2
              %span.txt1.p-b-20
                Address
              %span.txt2
                Mada Center 8th floor, 379 Hudson St, New York, NY 10018 US
          .dis-flex.size1.p-b-47
            .txt1.p-r-25
              %span.lnr.lnr-phone-handset
            .flex-col.size2
              %span.txt1.p-b-20
                Lets Talk
              %span.txt3
                +1 800 1236879
          .dis-flex.size1.p-b-47
            .txt1.p-r-25
              %span.lnr.lnr-envelope
            .flex-col.size2
              %span.txt1.p-b-20
                General Support
              %span.txt3
                contact@example.com
    #dropDownSelect1
    / ===============================================================================================
    %script{:src => "vendor/jquery/jquery-3.2.1.min.js"}
    / ===============================================================================================
    %script{:src => "vendor/animsition/js/animsition.min.js"}
    / ===============================================================================================
    %script{:src => "vendor/bootstrap/js/popper.js"}
    %script{:src => "vendor/bootstrap/js/bootstrap.min.js"}
    / ===============================================================================================
    %script{:src => "vendor/select2/select2.min.js"}
    :javascript
      $(".selection-2").select2({
      	minimumResultsForSearch: 20,
      	dropdownParent: $('#dropDownSelect1')
      });
    / ===============================================================================================
    %script{:src => "vendor/daterangepicker/moment.min.js"}
    %script{:src => "vendor/daterangepicker/daterangepicker.js"}
    / ===============================================================================================
    %script{:src => "vendor/countdowntime/countdowntime.js"}
    / ===============================================================================================
    %script{:src => "js/main.js"}
    / Global site tag (gtag.js) - Google Analytics
    %script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"}
    :javascript
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-23581568-13');

app/views/contacts/contact.html.haml
- if notice.present?
  .alert.alert-success.success_message #{t(:flash)[:success]}
.container-contact100
  .wrap-contact100
    .contact100-form
      %div.max_width
        = form_tag root_path, class: 'locale'  do
          = select_tag 'set_locale',                         |
            options_for_select(LANGUAGES, I18n.locale.to_s), |
            onchange: 'this.form.submit()'
      = form_with(url: contacts_path(@locale), method: "post", local: true, :class => "validate-form max_width" ) do
        %span.contact100-form-title.contact-title
          = t(:caption)[:message]
        %label.label-input100{:for => "first-name"} #{t(:labels)[:name]} *
        .div_flex
          .wrap-input100.rs1-wrap-input100.validate-input{"data-validate" => "Type first name"}
            %input#first-name.input100{:name => "first-name", :placeholder => "#{t(:placeholder)[:first_name]}", :type => "text"}/
            %span.focus-input100
          .wrap-input100.rs2-wrap-input100.validate-input{"data-validate" => "Type last name"}
            %input.input100{:name => "last-name", :placeholder => "#{t(:placeholder)[:last_name]}", :type => "text"}/
            %span.focus-input100
        %label.label-input100{:for => "email"} #{t(:labels)[:email]} *
        .wrap-input100.validate-input{"data-validate" => "Valid email is required: ex@abc.xyz"}
          %input#email.input100{:name => "email", :placeholder => "#{t(:placeholder)[:eg]}.#{t(:placeholder)[:example]}@email.com", :type => "text"}/
          %span.focus-input100
        %label.label-input100{:for => "phone"} #{t(:labels)[:email]}
        .wrap-input100
          %input#phone.input100{:name => "phone", :placeholder => "#{t(:placeholder)[:eg]}. +1 800 000000", :type => "text"}/
          %span.focus-input100
        %label.label-input100{:for => "message"} #{t(:labels)[:email]} *
        .wrap-input100.validate-input{"data-validate" => "Message is required"}
          %textarea#message.input100{:name => "message", :placeholder => t(:placeholder)[:message]}
          %span.focus-input100
        .container-contact100-form-btn
          %button.contact100-form-btn
            = t(:actions)[:send_message]
    .contact100-more.flex-col-c-m.back-image
      .flex-w.size1.p-b-47
        .txt1.p-r-25
          %span.lnr.lnr-map-marker
        .flex-col.size2
          %span.txt1.p-b-20
            = t(:labels)[:address]
          %span.txt2
            Mada Center 8th floor, 379 Hudson St, New York, NY 10018 US
      .dis-flex.size1.p-b-47
        .txt1.p-r-25
          %span.lnr.lnr-phone-handset
        .flex-col.size2
          %span.txt1.p-b-20
            = t(:labels)[:corporate_phone]
          %span.txt3
            +1 800 1236879
      .dis-flex.size1.p-b-47
        .txt1.p-r-25
          %span.lnr.lnr-envelope
        .flex-col.size2
          %span.txt1.p-b-20
            = t(:labels)[:support]
          %span.txt3
            contact@example.com
#dropDownSelect1
/ ===============================================================================================
%script{:src => "assets/vendor/jquery/jquery-3.2.1.min.js"}
/ ===============================================================================================
%script{:src => "assets/vendor/animsition/js/animsition.min.js"}
/ ===============================================================================================
%script{:src => "assets/vendor/bootstrap/js/popper.js"}
%script{:src => "assets/vendor/bootstrap/js/bootstrap.min.js"}
/ ===============================================================================================
%script{:src => "assets/vendor/select2/select2.min.js"}
:javascript
  $(".selection-2").select2({
  	minimumResultsForSearch: 20,
  	dropdownParent: $('#dropDownSelect1')
  });
/ ===============================================================================================
%script{:src => "assets/vendor/daterangepicker/moment.min.js"}
%script{:src => "assets/vendor/daterangepicker/daterangepicker.js"}
/ ===============================================================================================
%script{:src => "assets/vendor/countdowntime/countdowntime.js"}
/ ===============================================================================================
%script{:src => "assets/js/main.js"}
/ Global site tag (gtag.js) - Google Analytics
%script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"}
:javascript
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HiddenFacts
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    = favicon_link_tag asset_path("/icons/favicon.ico"), :rel => 'icon', :type =>  'image/png'
    / ===============================================================================================
    = stylesheet_link_tag "vendor/bootstrap/css/bootstrap.min.css"
    / ===============================================================================================
    = stylesheet_link_tag "fonts/font-awesome.min.css"
    / ===============================================================================================
    = stylesheet_link_tag "fonts/icon-font.min.css"
    / ===============================================================================================
    = stylesheet_link_tag "vendor/animate/animate.css"
    / ===============================================================================================
    = stylesheet_link_tag "vendor/css-hamburgers/hamburgers.min.css"
    / ===============================================================================================
    = stylesheet_link_tag "vendor/animsition/css/animsition.min.css"
    / ===============================================================================================
    = stylesheet_link_tag "vendor/select2/select2.min.css"
    / ===============================================================================================
    = stylesheet_link_tag "vendor/daterangepicker/daterangepicker.css"
    / ===============================================================================================
    = stylesheet_link_tag "css/util.css"
    = stylesheet_link_tag "css/main.css"
    / ===============================================================================================
  %body
    = yield